# NumPy

## Устанавливаем библиотеку

Для установки библиотеки `NumPy` необходимо использовать команду:
```
pip install numpy
```

## Проверяем доступность библиотеки

In [1]:
try:
    import numpy as np
    print("Версия библиотеки:", np.__version__)
except:
    print("Библиотека NumPy недоступна.")
    print("Установите ее при помощи команды 'pip install numpy")

Версия библиотеки: 1.25.2


## NumPy на примере

Создадим массив:

In [2]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

Создадим последовательность с шагом `0.6`:

In [3]:
np.arange(0, 2, 0.6)

array([0. , 0.6, 1.2, 1.8])

Создадим равномерный набор точек:

```python
np.linspace(start, stop[, num, ...])
```
* `start` - первое число
* `stop` - последнее число
* `num` - количество чисел

In [4]:
np.linspace(0, 1.13, 10)

array([0.        , 0.12555556, 0.25111111, 0.37666667, 0.50222222,
       0.62777778, 0.75333333, 0.87888889, 1.00444444, 1.13      ])

Создадим логарифмический набор точек:

In [5]:
np.logspace(2, 8, num=6, base=3)

array([   9.        ,   33.63473537,  125.69949149,  469.76323692,
       1755.59579557, 6561.        ])

Инициализация массива (ячейки заполняются случайными числами)

In [6]:
np.empty([3, 3])

array([[0.12555556, 0.25111111, 0.37666667],
       [0.50222222, 0.62777778, 0.75333333],
       [0.87888889, 1.00444444, 1.13      ]])

Создадим двухмерный диагональный единичный массив со сдвигом на `k`:

In [7]:
np.eye(10, k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Создадим двухмерный диагональный произвольный массив:

In [8]:
np.diag([8,4,2435,19,-435,0,7])

array([[   8,    0,    0,    0,    0,    0,    0],
       [   0,    4,    0,    0,    0,    0,    0],
       [   0,    0, 2435,    0,    0,    0,    0],
       [   0,    0,    0,   19,    0,    0,    0],
       [   0,    0,    0,    0, -435,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    7]])

Инициализируем массивы с единицами, а затем с нулями:

In [9]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Создаем нижнюю треугольную матрицу из единиц:

In [11]:
np.tri(4,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

Вырежем нижнюю треугольную матрицу:

In [12]:
arr = np.empty([4,4], dtype=int)
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.tril(arr))

Исходный массив:
 [[94820180328829              0   489626271861   433791696995]
 [  498216206368   468151435365   476741369968   416611827826]
 [  450971566194   519691042924   502511173664   416611827822]
 [  416611827830   463856468073   420906795105   433791697004]]
Полученный массив:
[[94820180328829              0              0              0]
 [  498216206368   468151435365              0              0]
 [  450971566194   519691042924   502511173664              0]
 [  416611827830   463856468073   420906795105   433791697004]]


Переопределяем форму массива с возможностью циклического автозаполнения, если будут оставаться пустые ячейки

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.resize(arr, [3,6]))

Исходный массив:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Полученный массив:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16  1  2]]


Переопределим форму массива без возможности циклического автозаполнения (**количество ячеек в новом массиве должно совпадать с количеством в исходном**)

In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.reshape(arr, [8,2]))

Исходный массив:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Полученный массив:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


Перобразуем исходный массив в новый одномерный:

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.ravel(arr))

Исходный массив:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Полученный массив:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


Сбор одномерных массивов-столбцов в двухмерный.

In [16]:
tup = ([1,2,3, 4, 100], [5,6,7,8, 101], [9,10,11,12, 102], [13,14,15,16, 103])
np.column_stack(tup)

array([[  1,   5,   9,  13],
       [  2,   6,  10,  14],
       [  3,   7,  11,  15],
       [  4,   8,  12,  16],
       [100, 101, 102, 103]])

Соединим последовательность массивов вместе

In [17]:
arr1 = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
arr2 = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
tup = (arr1, arr2)
np.concatenate(tup)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Повернем массив на $180\degree$

In [18]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.rot90(arr, k=2))

Исходный массив:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Полученный массив:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Проверим элементы массива на действительность

In [19]:
arr = np.array([[1, 2, 3, 4], [5j, 6j, 7j, 8j], [9j, 10j, 11, 12], [13j, 14, 15, 16]])
print("Исходный массив:\n", arr)
print("Полученный массив:")
print(np.isreal(arr))

Исходный массив:
 [[ 1. +0.j  2. +0.j  3. +0.j  4. +0.j]
 [ 0. +5.j  0. +6.j  0. +7.j  0. +8.j]
 [ 0. +9.j  0.+10.j 11. +0.j 12. +0.j]
 [ 0.+13.j 14. +0.j 15. +0.j 16. +0.j]]
Полученный массив:
[[ True  True  True  True]
 [False False False False]
 [False False  True  True]
 [False  True  True  True]]


Перемножение и сложение массивов:

In [20]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# Перемножим массивы arr1 и arr1 (возведем в степень 2)
arr2 = np.multiply(arr1, arr1)
print("Результат после умножения:")
print("Массив 1:\n", arr1)
print("Массив 2:\n", arr2)
# Сложим массивы arr1 и arr2 с сохранение результата в arr2
np.add(arr1, arr2, arr2)
print("Результат после сложения:")
print("Массив 1:\n", arr1)
print("Массив 2:\n", arr2)


Результат после умножения:
Массив 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Массив 2:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
Результат после сложения:
Массив 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Массив 2:
 [[  2   6  12  20]
 [ 30  42  56  72]
 [ 90 110 132 156]
 [182 210 240 272]]


Попробуем перемножить и сложить массивы более наглядно (при помощи использования операторов)

In [21]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# arr1 * arr1 <=> arr1 ** 2
arr2 = arr1**2
print("Результат после умножения:")
print("Массив 1:\n", arr1)
print("Массив 2:\n", arr2)
arr2 += arr1
print("Результат после сложения:")
print("Массив 1:\n", arr1)
print("Массив 2:\n", arr2)

Результат после умножения:
Массив 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Массив 2:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
Результат после сложения:
Массив 1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Массив 2:
 [[  2   6  12  20]
 [ 30  42  56  72]
 [ 90 110 132 156]
 [182 210 240 272]]


Сравним (`>`) массивы (по элементам):

In [22]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2 = arr1**2
print("arr1 > arr2?", np.greater(arr1, arr2))
# Равносильная операция
print("arr1 > arr2?", arr1 > arr2)

arr1 > arr2? [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
arr1 > arr2? [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


Найдем максимальные элементы из массивов (по элементам):

In [23]:
arr1 = [1,8,9,0]
arr2 = [4,5,6,7]
np.maximum(arr1, arr2)

array([4, 8, 9, 7])

Отсортируем массив:

In [24]:
arr = np.array([[1,4,1,-435,2,-4], [4,25,1,34,-234, 4]])
print("Массив до сортировки:\n",
      arr,
      "\nМассив после сортировки:")
arr2 = np.sort(arr)
print(arr2)


Массив до сортировки:
 [[   1    4    1 -435    2   -4]
 [   4   25    1   34 -234    4]] 
Массив после сортировки:
[[-435   -4    1    1    2    4]
 [-234    1    4    4   25   34]]


Отсортируем массив на месте:

In [25]:
arr = np.array([[1,4,1,-435,2,-4], [4,25,1,34,-234, 4]])
print("Массив до сортировки:\n",
      arr,
      "\nМассив после сортировки:")
arr.sort()
print(arr)


Массив до сортировки:
 [[   1    4    1 -435    2   -4]
 [   4   25    1   34 -234    4]] 
Массив после сортировки:
[[-435   -4    1    1    2    4]
 [-234    1    4    4   25   34]]


Вычислим определитель матрицы:

In [26]:
arr = np.array([[1,2],[3,4]])
# 1*4 - 2*3 = 4-6 = -2
np.linalg.det(arr)

-2.0000000000000004

Найдем обратную матрицу

In [27]:
arr1 = np.array([[2,4], [4,5]])
# Ищем определитель
det = np.linalg.det(arr1)
if det:
    print("Определитель матрицы равен:", det)
    # Ищем обратную матрицу
    arr2 = np.linalg.inv(arr1)
    print("Исходная матрица:")
    print(arr1)
    print("\nОбратная матрица:")
    print(arr2)
    # Проверяем корректность расчета
    # перемножив исходную матрицу на обратную
    mult_arr = arr1.dot(arr2)
    # Проверяем соответствие полученно
    check_result = np.eye(2) == mult_arr
    print("\nРезультата проверки\n", check_result)
else:
    print("Операция невозможна. Определитель равен нулю.")

Определитель матрицы равен: -6.0
Исходная матрица:
[[2 4]
 [4 5]]

Обратная матрица:
[[-0.83333333  0.66666667]
 [ 0.66666667 -0.33333333]]

Результата проверки
 [[ True  True]
 [ True  True]]


Создадим набор случайных чисел заданной формы:

In [28]:
import numpy.random as rnd

rnd.rand(2,2)

array([[0.54837972, 0.05299544],
       [0.85146308, 0.38850821]])

Создадим случайное целое число при помощи `randint(low[, high, size])`
* low - от (включая);
* high - до (не включая);
* size - число элементов по каждому измерению

In [29]:
rnd.randint(3,7 + 1)

5

Теперь создадим одномерный массив (случайные числа от 0 до 100):

In [30]:
rnd.randint(0,100 + 1, 10)

array([56, 17, 98, 17, 46, 93, 51, 86, 67, 30])

Создадим двухмерный массив (4 на 5) со случайными числами от 0 до 10:

In [31]:
rnd.randint(0, 10 + 1, [4,5])

array([[ 1,  3,  3,  4,  0],
       [ 0,  5, 10,  9,  3],
       [ 4,  7,  5,  3,  3],
       [ 1,  6,  7,  7,  6]])

Сделаем перемешивание массива **на месте**:

In [32]:
arr = rnd.randint(0, 100 + 1, 10)
print("Исходный массив:", arr)
for i in np.arange(0, 9):
    # Перемешиваем массив на месте
    rnd.shuffle(arr)
    print(i+1, "shuffle ->", arr)

Исходный массив: [78 17 38 47 66 67  1 49 29 83]
1 shuffle -> [66 78 17  1 83 47 38 29 49 67]
2 shuffle -> [29 78 49 66 67 47  1 17 83 38]
3 shuffle -> [66 17 83 67  1 29 49 78 47 38]
4 shuffle -> [49 78 66 38 29 47  1 83 67 17]
5 shuffle -> [17 38 83 49  1 66 29 67 47 78]
6 shuffle -> [ 1 49 67 47 78 17 29 66 83 38]
7 shuffle -> [47  1 49 78 17 67 29 66 38 83]
8 shuffle -> [78  1 83 17 67 38 66 29 47 49]
9 shuffle -> [67 49 17  1 66 83 78 38 47 29]


Сделаем перемешивание массива без изменения исходного:

In [33]:
arr = rnd.randint(0, 100 + 1, 10)
print("Исходный массив:", arr)
for i in np.arange(0, 9):
    print(i+1, "shuffle ->", rnd.permutation(arr))

Исходный массив: [67 31 26 42 73 80 51 10 25 23]
1 shuffle -> [80 42 67 25 26 10 51 23 73 31]
2 shuffle -> [80 51 67 31 10 26 23 25 73 42]
3 shuffle -> [73 25 31 10 67 26 42 23 51 80]
4 shuffle -> [25 51 67 80 23 42 73 26 31 10]
5 shuffle -> [26 73 42 80 25 51 67 31 10 23]
6 shuffle -> [23 51 80 73 67 31 42 26 10 25]
7 shuffle -> [42 10 31 26 67 80 25 23 51 73]
8 shuffle -> [51 73 25 31 26 80 42 10 23 67]
9 shuffle -> [51 23 10 25 73 42 31 80 26 67]


Найдем максимум и минимум в массиве:

In [34]:
arr = rnd.randint(0, 16, [3,3])
print("Исходный массив:", arr)
print("Минимум:", np.amin(arr))
print("Максимум:", np.amax(arr))

Исходный массив: [[1 1 4]
 [0 5 7]
 [0 6 2]]
Минимум: 0
Максимум: 7
